[package]
name = "lcs_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
indexmap = "2.7.1"
lcs = { path = "../lcs" }
serde = "1.0.217"
serde-wasm-bindgen = "0.6.5"
tsify = { version = "0.4.5", features = ["js"] }
wasm-bindgen = "0.2.100"
