[package]
name = "lcs"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
enum-as-inner = "0.6.1"
indexmap = "2.6.0"
itertools = "0.13.0"
maplit = "1.0.2"
ordermap = "0.5.3"
termtree = "0.5.1"
winnow = "0.6.20"
