[package]
name = "lcs"
version = "0.1.0"
edition = "2021"

[dependencies]
as_variant = "1.2.0"
colored = "2.1.0"
derive_more = { version = "1.0.0", features = ["full"] }
enum-as-inner = "0.6.1"
indexmap = "2.6.0"
itertools = "0.13.0"
maplit = "1.0.2"
ordermap = "0.5.3"
replace_with = "0.1.7"
termtree = "0.5.1"
unlatex = "0.1.0"
winnow = "0.6.20"
